name: automerge
on:
  push:
    branches: [release/*]

concurrency:
  group: automerge-${{ github.ref }}
  cancel-in-progress: true

jobs:
  automerge:
    if: github.repository == 'carbon-design-system/carbon-labs'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Merge to main
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: 'main'
          github_token: ${{secrets.MERGE_ACTION}}
