name: ci-check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dedupe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Use Node.js 18.x
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: '18.x'
      - name: Run yarn dedupe
        run: yarn dedupe --check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 18.x
        uses: actions/setup-node@v6
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Run build
        run: yarn build
      - name: Run CDN (dist) build
        run: yarn build:dist

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 18.x
        uses: actions/setup-node@v6
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Check formatting of project files (staged)
        if: ${{ github.event_name == 'pull_request' }}
        run: yarn format:diff
      - name: Check formatting of project files (non-staged)
        if: ${{ github.event_name != 'pull_request' }}
        run: yarn format

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 18.x
        uses: actions/setup-node@v6
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint && yarn lint:styles

  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 18.x
        uses: actions/setup-node@v6
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: License check
        run: yarn lint:license

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 18.x
        uses: actions/setup-node@v6
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Run build
        run: yarn build
      - name: run React tests
        working-directory: 'packages/react'
        run: yarn test
      - name: run Web Component tests
        working-directory: 'packages/web-components'
        run: yarn test
      - name: run VSCode Snippets tests
        working-directory: 'packages/vscode-snippets'
        run: yarn test
