name: Publish CDN artifacts (canary) to S3
on:
  push:
    branches:
      - main

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-canary-cdn:
    if: github.repository == 'carbon-design-system/carbon-labs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: '0'
      - uses: fkirc/skip-duplicate-actions@v5.3.1
        with:
          github_token: ${{ github.token }}
      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Build packages
        run: yarn build
      - name: Build dist folders in each package
        run: yarn build:dist:canary
      - name: Create one folder with dist contents from each package
        working-directory: 'packages/web-components'
        run: |
          mkdir dist
          cp -r src/components/**/dist/. dist/
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.COMMON_COS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.COMMON_COS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COMMON_COS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.COMMON_COS_REGION }}
          AWS_S3_ENDPOINT: https://${{ secrets.COMMON_COS_ENDPOINT }}
          SOURCE_DIR: 'dist'
          DEST_DIR: 'common/carbon/labs/web-components'
